# -*- coding: utf-8 -*-
"""Rag_transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPR5Eax32_-kwv0S7lDTgwkTDeD36ZR3
"""

from transformers import pipeline

pipe = pipeline("text-generation", model="Qwen/Qwen2.5-1.5B-Instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

q1="what is AI"
result=pipe(q1,max_new_tokens=50)
print(result)



from huggingface_hub import login
login()

from transformers import pipeline

pipe = pipeline("text-generation", model="meta-llama/Llama-3.2-1B-Instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

q1="what is cricket"
result=pipe(q1,max_new_tokens=50)
print(result)
